### ISSUE TITLE
HTTP does not pause WebSocket operations during pending reconnect

### ISSUE THREAD

**Issue by valzargaming** [discord-php/DiscordPHP#1228]
**Environment**
- PHP Version:
    - 8.3.6
- DiscordPHP Version:
    - dev-master

**Describe the bug**
The library continues to attempt operations on the WebSocket while a reconnect is pending, instead of waiting for the reconnection to complete. This can lead to failed requests and unexpected errors.

**To Reproduce**
Attempt to perform any API calls after op code 1000 is received but before the socket is reconnected, which should happen automatically after 2 seconds.

**Expected behavior**
The library should not attempt to perform any functions other than reconnect while the websocket is knowingly disconnected. Any other API-related promises that are created during this time should be deferred.

**Additional context**
```php
[2024-05-19T18:13:03.191376+00:00] Civ13.WARNING: REQ POST channels/690025163634376738/messages failed: Connection to tls://discord.com:443 timed out after 60 seconds (ETIMEDOUT)
[2024-05-19T18:13:03.192807+00:00] Civ13.WARNING: websocket closed {"op":1000,"reason":""}
[2024-05-19T18:13:03.192853+00:00] Civ13.WARNING: reconnecting in 2 seconds
[2024-05-19T18:13:03.194160+00:00] Civ13.WARNING: REQ PATCH channels/1231988255470125117 failed: Connection to tls://discord.com:443 failed during TLS handshake: Connection lost during TLS handshake (ECONNRESET)
[2024-05-19T18:13:03.194254+00:00] Civ13.ERROR: Promise rejected with reason: `RuntimeException: Connection to tls://discord.com:443 failed during TLS handshake: Connection lost during TLS handshake (ECONNRESET) in /home/civ13/Civilizationbot/vendor/react/socket/src/SecureConnector.php:68
Stack trace:
#0 /home/civ13/Civilizationbot/vendor/react/promise/src/RejectedPromise.php(28): React\Socket\SecureConnector->React\Socket\{closure}()
#1 /home/civ13/Civilizationbot/vendor/react/socket/src/SecureConnector.php(64): React\Promise\RejectedPromise->then()
#2 /home/civ13/Civilizationbot/vendor/react/promise/src/FulfilledPromise.php(28): React\Socket\SecureConnector->React\Socket\{closure}()
#3 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#4 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#5 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#6 /home/civ13/Civilizationbot/vendor/react/promise/src/FulfilledPromise.php(28): React\Promise\Promise::React\Promise\{closure}()
#7 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#8 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#9 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#10 /home/civ13/Civilizationbot/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#11 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done()
#12 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#13 /home/civ13/Civilizationbot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#14 /home/civ13/Civilizationbot/vendor/react/socket/src/TcpConnector.php(145): React\Promise\Promise::React\Promise\{closure}()
#15 /home/civ13/Civilizationbot/vendor/react/event-loop/src/StreamSelectLoop.php(254): React\Socket\TcpConnector->React\Socket\{closure}()
#16 /home/civ13/Civilizationbot/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#17 /home/civ13/Civilizationbot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1491): React\EventLoop\StreamSelectLoop->run()
#18 /home/civ13/Civilizationbot/src/Civ13.php(797): Discord\Discord->run()
#19 /home/civ13/Civilizationbot/bot.php(429): Civ13\Civ13->run()
#20 {main}'`
```

**Comment by pro2s** [comment]
is there a workaround for this issue? check the connection or something else before requesting.

**Comment by valzargaming** [comment]
> is there a workaround for this issue? check the connection or something else before requesting.

I have been unable to come up with a feasible workaround due to the primary $discord object not making its WebSocket instance of $ws publicly accessible.

**Comment by valzargaming** [comment]
I've come up with one possible solution to this so far, however with Promises v2 the only way to effectively implement it is from userland. A workaround would involve implementing a middleware that handles the callback results for all `->then(` statements and listening for the result. If the promise rejects with reason `RuntimeException: Connection to tls://discord.com:443 timed out after 60 seconds (ETIMEDOUT)` then the promise should be deferred and reattempted at a later time.

This will likely be possible to implement into the library whenever we can upgrade to Promises v3 when we will be able to utilize [set_rejection_handler](https://reactphp.org/promise/#set_rejection_handler).

**Comment by SQKo** [comment]
Ideally we should Pause the loop of the Discord-PHP Http, but since it's not practically possible with React Event loop, the solution to this is to rewrite the Discord-PHP Http queuing mechanism to allow requests to be paused and hold back in the bucket instead of forwarding the network issue as rejection and attempt to recreate the promise which could be indefinite

**Comment by valzargaming** [comment]
I believe this issue should now 'softly' be considered as resolved. The exact details of how the client should respond to a timeout will likely vary from person to person, and as such anyone needing special handling should `extend` the Discord class and implement their own handling methods.

**Comment by valzargaming** [comment]
Added the user bug tag as the fix for this should be handled by the user of the library as to what to do next. Listening for and catching this exception should allow for a user to manually recreate the Discord object, but an enhancement should be considered to make `$discord->connectWs()` public.

**Comment by valzargaming** [comment]
Further research is being done on how to improve connectivity with Discord and several changes have been made since this issue was opened. The root cause of this issue still persists, and the recommended action would be for userland implementations to utilize `React\Promise\set_rejection_handler`, `$discord->connectWs()`
  to potentially defer and retry Closing this for now, but will revisit this topic in the future
