### ISSUE TITLE
Return value of Discord\Parts\WebSockets\MessageReaction::getMemberAttribute() is instance of stdClass returned in MessageReaction.php

### ISSUE THREAD

**Issue by murdick** [discord-php/DiscordPHP#532]
**Environment**
- PHP Version:
    - 7.4.3
- DiscordPHP Version:
    - v6.0.1

**Describe the bug**
Working with the return from reaction collection produces a crash, that starts with a warning about stdClass being returned from getMemberAttribute.

**To Reproduce**
```php
$formmessage->createReactionCollector(function ($reaction) use (&$storage) {
  return true;
}, ['time' => false, 'limit' => 3])->done(function ($reactions) use (&$storage, $formmessage) {
    var_dump($reactions);
}
```

**Expected behavior**
Variable to be populated with values, without crash. ;)

**Screenshots**
[crashcase.txt](https://github.com/discord-php/DiscordPHP/files/6517939/crashcase.txt)

**Additional context**
```  PHP Warning:  Uncaught TypeError: Return value of Discord\Parts\WebSockets\MessageReaction::getMemberAttribute() must be an instance of Discord\Parts\User\Member or null, instance of stdClass returned in /home/murdick/applicationbot/vendor/team-reflex/discord-php/src/Discord/Parts/WebSockets/MessageReaction.php:150
Stack trace:
#0 /home/murdick/applicationbot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(218): Discord\Parts\WebSockets\MessageReaction->getMemberAttribute()
#1 /home/murdick/applicationbot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(355): Discord\Parts\Part->getAttribute()
#2 /home/murdick/applicationbot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(430): Discord\Parts\Part->getPublicAttributes()
#3 [internal function]: Discord\Parts\Part->__debugInfo()
#4 /home/murdick/applicationbot/applicationbot.php(178): var_dump()
#5 /home/murdick/applicationbot/vendor/react/promise/src/FulfilledPromise.php(42): {closure}()
#6 /home/murdick/applicationbot/vendor/react/promise in /home/murdick/applicationbot/vendor/team-reflex/discord-php/src/Discord/Parts/WebSockets/MessageReaction.php on line 150
PHP Fatal error:  __debuginfo() must return an array in /home/murdick/applicationbot/applicationbot.php on line 178```

**Comment by davidcole1340** [comment]
Thanks, fixed on `master`.
