### ISSUE TITLE
Random script stop

### ISSUE THREAD

**Issue by xWildFire** [discord-php/DiscordPHP#573]
**Environment**
- PHP Version:
    - 8.0.9 (always latest)
- DiscordPHP Version:
    - v7.0.0-rc0 (always latest develop branch)

**Describe the bug**

```
[09.08.2021, 14:28:27] [INFO] Bot is starting... []
[09.08.2021, 14:28:27] [INFO] not starting http server - will wait for gateway events []
[09.08.2021, 14:28:28] [INFO] gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=9&encoding=json","session":{"total":1000,"remaining":996,"reset_after":13823865,"max_concurrency":1}}
[09.08.2021, 14:28:28] [INFO] starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=9&encoding=json"}
[09.08.2021, 14:28:28] [INFO] websocket connection has been created []
[09.08.2021, 14:28:28] [INFO] received hello []
[09.08.2021, 14:28:28] [INFO] heartbeat timer initilized {"interval":41250.0}
[09.08.2021, 14:28:28] [INFO] identifying {"payload":{"op":2,"d":{"token":"xxxxxx","properties":{"$os":"Linux","$browser":"DiscordBot (https://github.com/discord-php/DiscordPHP-HTTP, v9.0.0)","$device":"DiscordBot (https://github.com/discord-php/DiscordPHP-HTTP, v9.0.0)","$referrer":"https://github.com/discord-php/DiscordPHP","$referring_domain":"https://github.com/discord-php/DiscordPHP"},"compress":true,"intents":32767,"shard":[0,1]}}}
[09.08.2021, 14:28:28] [INFO] stored private channels {"count":0}
[09.08.2021, 14:28:28] [INFO] stored guilds {"count":0,"unavailable":1}
[09.08.2021, 14:28:29] [INFO] all guilds are now available {"count":1}
[09.08.2021, 14:28:29] [INFO] set up chunking, checking for chunks every 5 seconds []
[09.08.2021, 14:28:29] [INFO] client is ready []
[09.08.2021, 14:28:29] [INFO] Bot has fully started! []
[09.08.2021, 14:49:13] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 14:49:13] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 14:49:14] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 14:49:14] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 14:49:15] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:02:29] [WARNING] REQ PATCH channels/571065987219062842 hit rate-limit: RATELIMIT Non-global, retry after 59.99 s []
[09.08.2021, 15:30:17] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:30:17] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:30:18] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:30:18] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:30:19] [INFO] BUCKET putchannels/496578504972959746/messages/:message_id/reactions/:emoji/@me expecting rate limit, timer interval 250 ms []
[09.08.2021, 15:54:37] [WARNING] received opcode 7 for reconnect []
[09.08.2021, 15:54:37] [WARNING] websocket closed {"op":4000,"reason":"gateway redirecting - opcode 7"}
[09.08.2021, 15:54:37] [WARNING] reconnecting in 2 seconds []
[09.08.2021, 15:54:39] [INFO] starting reconnect {"reconnect_count":1}
[09.08.2021, 15:54:39] [INFO] gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=9&encoding=json","session":{"total":1000,"remaining":994,"reset_after":8651982,"max_concurrency":1}}
[09.08.2021, 15:54:39] [INFO] starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=9&encoding=json"}
[09.08.2021, 15:54:40] [INFO] websocket connection has been created []
[09.08.2021, 15:54:40] [INFO] received hello []
[09.08.2021, 15:54:40] [INFO] heartbeat timer initilized {"interval":41250.0}
[09.08.2021, 15:54:40] [INFO] resuming connection {"payload":{"op":6,"d":{"session_id":"5e18a0ee47e5c7ab83fec456dbe3dc6c","seq":15821,"token":"xxxxxx"}}}
[09.08.2021, 15:54:40] [INFO] websocket reconnected to discord []
[09.08.2021, 16:35:50] [WARNING] REQ GET guilds/484723871887392772/invites failed: Request timed out after 1 seconds []
[2021-08-09 16:35:50] Message: Request timed out after 1 seconds
	File: /var/www/metin2.priv.pl/discord_bot/vendor/react/http/src/Io/Transaction.php:130
	Trace:
		#0 /var/www/metin2.priv.pl/discord_bot/vendor/react/event-loop/src/Timer/Timers.php(96): React\Http\Io\Transaction->React\Http\Io\{closure}()
#1 /var/www/metin2.priv.pl/discord_bot/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick()
#2 /var/www/metin2.priv.pl/discord_bot/src/WildCord/App.php(292): React\EventLoop\StreamSelectLoop->run()
#3 /var/www/metin2.priv.pl/discord_bot/bot.php(10): WildCord\App->run()
#4 {main}
[09.08.2021, 16:35:50] [INFO] Bot loop died. []
[09.08.2021, 16:35:50] [INFO] discord closed []
```

or sometimes its going into zombie mode, receiving events but e.g cant send responding actions to them and i need to restart script to make it work again.

I don't know what is wrong with this, but from time to time my script shutdowns with this error for no reason.
My connection is stable and im not doing heavy things just some channel update every x minutes and giving roles by reaction.

**To Reproduce**

No idea.

**Expected behavior**

Work without stopping for no reason, maybe some catch on that error or something?

**Additional context**

This happens on dev version and on stable version too. I checked on different vps and its still happens.

**Comment by xWildFire** [comment]
Fixed your lib on my own. (:

**Comment by valzargaming** [comment]
@xWildFire I'd be interested to know what you did to get it working in your use-case. I've had a hard time replicating this, specifically because the only thing I've found to kill the loop are bits of user-defined code within the events handlers that end up blocking the process. In my own bot, moving all process-blocking functions into external scripts that make a call back to the bot via reactphp's server (so the whole bot acts like a Rest API) fixed it and I haven't had any such issues in months.
