### ISSUE TITLE
channel->deleteMessages Error

### ISSUE THREAD

**Issue by bozzes** [discord-php/DiscordPHP#588]
DiscordPHP.DEBUG: BUCKET deletechannels/878893211882508311/messages/:message_id queued REQ DELETE channels/878893211882508311/messages/:message_id [] []

DiscordPHP.DEBUG: BUCKET postchannels/878893211882508311/messages queued REQ POST channels/878893211882508311/messages [] []
[2021-08-24T23:17:49.976612+02:00] DiscordPHP.WARNING: REQ DELETE channels/878893211882508311/messages/:message_id failed: Discord\Http\Exceptions\RequestFailedException: Bad Request - {     "code": 50035,     "errors": {         "message_id": {             "_errors": [                 {                     "code": "NUMBER_TYPE_COERCE",                     "message": "Value \":message_id\" is not snowflake."                 }             ]         }     },     "message": "Invalid Form Body" } in C:\xampp\htdocs\bot\vendor\discord-php\http\src\Discord\Http.php:464 Stack trace: #0 C:\xampp\htdocs\bot\vendor\discord-php\http\src\Discord\Http.php(348): Discord\Http\Http->handleError(Object(RingCentral\Psr7\Response)) #1 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(42): Discord\Http\Http->Discord\Http\{closure}(Object(RingCentral\Psr7\Response)) #2 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure)) #3 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #4 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #5 C:\xampp\htdocs\bot\vendor\react\promise\src\Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) #6 C:\xampp\htdocs\bot\vendor\react\http\src\Io\Transaction.php(90): React\Promise\Deferred->resolve(Object(RingCentral\Psr7\Response)) #7 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(28): React\Http\Io\Transaction->React\Http\Io\{closure}(Object(RingCentral\Psr7\Response)) #8 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure)) #9 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #10 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #11 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) #12 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) #13 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #14 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #15 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) #16 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure)) #17 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #18 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #19 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) #20 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) #21 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #22 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #23 C:\xampp\htdocs\bot\vendor\react\promise\src\FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}('{"code": 50035,...') #24 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) #25 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) #26 C:\xampp\htdocs\bot\vendor\react\promise\src\Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) #27 C:\xampp\htdocs\bot\vendor\react\promise-stream\src\functions.php(75): React\Promise\Promise::React\Promise\{closure}('{"code": 50035,...') #28 C:\xampp\htdocs\bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Promise\Stream\{closure}() #29 C:\xampp\htdocs\bot\vendor\react\http\src\Io\ReadableBodyStream.php(50): Evenement\EventEmitter->emit('close') #30 C:\xampp\htdocs\bot\vendor\react\http\src\Io\ReadableBodyStream.php(151): React\Http\Io\ReadableBodyStream->close() #31 C:\xampp\htdocs\bot\vendor\react\http\src\Io\ReadableBodyStream.php(33): React\Http\Io\ReadableBodyStream->handleEnd() #32 C:\xampp\htdocs\bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Http\Io\ReadableBodyStream->React\Http\Io\{closure}('{"code": 50035,...') #33 C:\xampp\htdocs\bot\vendor\react\http\src\Client\Request.php(163): Evenement\EventEmitter->emit('data', Array) #34 C:\xampp\htdocs\bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Http\Client\Request->handleData('HTTP/1.1 400 Ba...') #35 C:\xampp\htdocs\bot\vendor\react\stream\src\Util.php(71): Evenement\EventEmitter->emit('data', Array) #36 C:\xampp\htdocs\bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('HTTP/1.1 400 Ba...') #37 C:\xampp\htdocs\bot\vendor\react\stream\src\DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array) #38 C:\xampp\htdocs\bot\vendor\react\event-loop\src\StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData(Resource id #242) #39 C:\xampp\htdocs\bot\vendor\react\event-loop\src\StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2495222) #40 C:\xampp\htdocs\bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(1368): React\EventLoop\StreamSelectLoop->run() #41 C:\xampp\htdocs\bot\bot.php(45): Discord\Discord->run() #42 {main} [] []

**this error appear when i tried to $message->channel->deleteMessages([ 'message_id' ]);**

**Comment by davidcole1340** [comment]
You are trying to delete a message with an ID `message_id`, which makes no sense, You put the message IDs or objects inside the array.
