### ISSUE TITLE
crashed when receiving message from thread

### ISSUE THREAD

**Issue by weichenlin** [discord-php/DiscordPHP#595]
**Environment**
- PHP Version:
    - PHP 8.0.7 (cli)
- DiscordPHP Version:
    - dev-develop
    - source   : [git] https://github.com/discord-php/DiscordPHP.git b8dca03091b2ee111fab0a062fcbc0306d53b192
    - dist     : [zip] https://api.github.com/repos/discord-php/DiscordPHP/zipball/b8dca03091b2ee111fab0a062fcbc0306d53b192 b8dca03091b2ee111fab0a062fcbc0306d53b192

**Describe the bug**
crash after run a few hours.
```
PHP Fatal error:  Uncaught TypeError: Discord\Discord::getChannel(): Return value must be of type ?Discord\Parts\Channel\Channel, Discord\Parts\Thread\Thread returned in /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php:1495
Stack trace:
#0 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php(247): Discord\Discord->getChannel()
#1 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(225): Discord\Parts\Channel\Message->getChannelAttribute()
#2 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(452): Discord\Parts\Part->getAttribute()
#3 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate.php(30): Discord\Parts\Part->__get()
#4 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php(722): Discord\WebSockets\Events\MessageCreate->handle()
#5 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php(587): Discord\Discord->handleDispatch()
#6 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage()
#7 /home/user/mybot/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
#8 /home/user/mybot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
#9 /home/user/mybot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#10 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#11 /home/user/mybot/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#12 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#13 /home/user/mybot/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#14 /home/user/mybot/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()
#15 /home/user/mybot/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#16 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1359): React\EventLoop\StreamSelectLoop->run()
#17 /home/user/mybot/bin/okpeko.php(228): Discord\Discord->run()
#18 {main}
  thrown in /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 1495
```

**To Reproduce**
receiving message from thread may trigger it.
I can't exactly reproduce it, but it happens 3 times today.

**Expected behavior**
no crash

**Comment by davidcole1340** [comment]
Should be fixed on the latest `master` version. Seems the problem was messages being updated, which caused a thread to be inserted into the channels repository.
