### ISSUE TITLE
Cannot identify reaction user/member on MESSAGE_REACTION_REMOVE

### ISSUE THREAD

**Issue by jocafamaka** [discord-php/DiscordPHP#600]
**Environment**
- PHP Version:
    - 7.4.22
- DiscordPHP Version:
    - 6.0.2
    -  dev-develop

**Describe the bug**
When receiving the <code>MESSAGE_REACTION_REMOVE</code> event when trying to fetch attributes the console print a bunch of errors and we cannot access any attributes as is null or empty array, when trying to print the class, a fatal error occurs.

**To Reproduce**
```php
$discord->on(Event::MESSAGE_REACTION_REMOVE, function (MessageReaction $reaction, Discord $discord) {
    $reaction->fetch()->done(function (MessageReaction $reaction) use ($discord) {
        echo($reaction->user->id);
        print_r($reaction);
    });
});
```

**Expected behavior**
Reaction attributes must be fetched without errors.

**Screenshots**

Debug log
```
Notice: Undefined index: user in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 335

Notice: Trying to get property 'id' of non-object in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 335

Notice: Undefined index: user in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 339

Notice: Undefined index: user in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 335

Notice: Trying to get property 'id' of non-object in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 335

Notice: Undefined index: user in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 339

Notice: Undefined index: user in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 304

Notice: Trying to get property 'id' of non-object in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 304

Warning: Uncaught TypeError: Return value of Discord\Parts\User\Member::getIdAttribute() must be of the type string, null returned in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php:304
Stack trace:
#0 /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(225): Discord\Parts\User\Member->getIdAttribute()
#1 /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(362): Discord\Parts\Part->getAttribute('id')
#2 /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php(437): Discord\Parts\Part->getPublicAttributes()
#3 [internal function]: Discord\Parts\Part->__debugInfo()
#4 /path_to/bot/bot.php(255): print_r(Object(Discord\Parts\WebSockets\MessageReaction))
#5 /path_to/bot/vendor/react/promise/src/FulfilledPromise.php(42): {closure}(Object(Discord\Parts\WebSockets\MessageReaction))
#6 /path_to/bot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(O in /path_to/bot/vendor/team-reflex/discord-php/src/Discord/Parts/User/Member.php on line 304

Fatal error: __debuginfo() must return an array in /path_to/bot/bot.php on line 255
```

**Additional context**
I believe it has something to do with binding of the attributes or something like that, when the event is <code>MESSAGE_REACTION_ADD</code> the fetch works normal, but I could debug that in this case it does not fetch the user/member, as it is not null like happens with <code>MESSAGE_REACTION_REMOVE</code>, and when logging the DISCORD API responses do not show any apparent errors and the data is in standard format.

**Comment by jocafamaka** [comment]
After some debug I came to the conclusion that the behavior of not having the user's instance makes sense, once the reaction was removed.

I saw that it is possible to identify the user through the <code>user_id</code> attribute.
