### ISSUE TITLE
bad request on set guild banner

### ISSUE THREAD

**Issue by weichenlin** [discord-php/DiscordPHP#629]
**Environment**
- PHP Version:
    - PHP 8.0.7
- DiscordPHP Version:
    - v6.0.2

**Describe the bug**
I have a bot to change guild banner, it works well before.
but today I found it got Bad Request when changing banner.
likely discord changed something, the region value from `$guild->getPublicAttributes()` is `"deprecated"`,
and I found DiscordPHP has `"region":"deprecated"` in the request.

the error msg is:
```txt
REQ PATCH guilds/------------ failed: Discord\Http\Exceptions\RequestFailedException: Bad Request -
 {
     "code": 50035,
     "errors": {
         "region": {
             "_errors": [
                 {
                     "code": "BASE_TYPE_CHOICES",
                     "message": "Value must be one of ('us-west', 'sydney', 'europe', 'eu-central', 'santiago', 'hongkong', 'brazil', 'us-south', 'vip-us-west', 'rotterdam', 'vip-amsterdam', 'stockholm', 'us-central', 'frankfurt', 'south-korea', 'st-pete', 'singapore', 'santa-clara', 'amsterdam', 'russia', 'london', 'us-east', 'india', 'dubai', 'seattle', 'eu-west', 'buenos-aires', 'southafrica', 'newark', 'vip-us-east', 'atlanta', 'japan')."
                 }
             ]
         }
     },
     "message": "Invalid Form Body"
 } 
in /home/user/mybot/vendor/discord-php/http/src/Discord/Http.php:466 Stack trace: 
#0 /home/user/mybot/vendor/discord-php/http/src/Discord/Http.php(348): Discord\Http\Http->handleError(Object(RingCentral\Psr7\Response)) 
#1 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(42): Discord\Http\Http->Discord\Http\{closure}(Object(RingCentral\Psr7\Response)) 
#2 /home/user/mybot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure)) 
#3 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#4 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#5 /home/user/mybot/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) 
#6 /home/user/mybot/vendor/react/http/src/Io/Transaction.php(90): React\Promise\Deferred->resolve(Object(RingCentral\Psr7\Response)) 
#7 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Io\Transaction->React\Http\Io\{closure}(Object(RingCentral\Psr7\Response)) 
#8 /home/user/mybot/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure)) 
#9 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#10 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#11 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) 
#12 /home/user/mybot/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) 
#13 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#14 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#15 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) 
#16 /home/user/mybot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure)) 
#17 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#18 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#19 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response)) 
#20 /home/user/mybot/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) 
#21 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#22 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#23 /home/user/mybot/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}('{"code": 50035,...') 
#24 /home/user/mybot/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure)) 
#25 /home/user/mybot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise)) 
#26 /home/user/mybot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise)) 
#27 /home/user/mybot/vendor/react/promise-stream/src/functions.php(79): React\Promise\Promise::React\Promise\{closure}('{"code": 50035,...') 
#28 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}() 
#29 /home/user/mybot/vendor/react/http/src/Io/ReadableBodyStream.php(50): Evenement\EventEmitter->emit('close') 
#30 /home/user/mybot/vendor/react/http/src/Io/ReadableBodyStream.php(151): React\Http\Io\ReadableBodyStream->close() 
#31 /home/user/mybot/vendor/react/http/src/Io/ReadableBodyStream.php(33): React\Http\Io\ReadableBodyStream->handleEnd() 
#32 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\ReadableBodyStream->React\Http\Io\{closure}('{"code": 50035,...') 
#33 /home/user/mybot/vendor/react/http/src/Client/Request.php(163): Evenement\EventEmitter->emit('data', Array) 
#34 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Client\Request->handleData('HTTP/1.1 400 Ba...') 
#35 /home/user/mybot/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array) 
#36 /home/user/mybot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('HTTP/1.1 400 Ba...') 
#37 /home/user/mybot/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array) 
#38 /home/user/mybot/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData(Resource id #234) 
#39 /home/user/mybot/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2692573) 
#40 /home/user/mybot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1368): React\EventLoop\StreamSelectLoop->run() 
#41 /home/user/mybot/bin_debug/testBanner.php(85): Discord\Discord->run() 
#42 {main}
```

**To Reproduce**
```php
$guild->fill([
    'banner' => $base64Image,
]);
$discord->guilds->save($guild)
```

**Expected behavior**
banner got changed without error

**Additional context**
for anyone got same issue, add a region field can fix this error.
```php
$guild->fill([
    'banner' => $base64Image,
    'region' => "japan"
]);
$discord->guilds->save($guild)
```

**Comment by davidcole1340** [comment]
Try on latest `master` branch please
