### ISSUE TITLE
loadAllMembers does not work on 32-bits PHP with large guilds

### ISSUE THREAD

**Issue by SQKo** [discord-php/DiscordPHP#685]
Enabling `loadAllMembers` options running on 32-bits PHP when the bot is at least in one of guild considered "large" will crash after chunking up the members:
```
[2022-01-20T04:29:43.510365+00:00] DiscordPHP.DEBUG: guild available {"guild":"872531095621615646","unavailable":1} []
[2022-01-20T04:29:43.511365+00:00] DiscordPHP.INFO: all guilds are now available {"count":2} []
[2022-01-20T04:29:43.511365+00:00] DiscordPHP.INFO: set up chunking, checking for chunks every 5 seconds [] []
[2022-01-20T04:29:43.511365+00:00] DiscordPHP.DEBUG: sending 1 chunks with 2 large guilds overall [] []
[2022-01-20T04:29:43.511365+00:00] DiscordPHP.DEBUG: sending chunk with 2 large guilds [] []
PHP Warning:  unpack(): 64-bit format codes are not available for 32-bit versions of PHP in D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php on line 163
PHP Notice:  Trying to access array offset on value of type bool in D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php on line 163
PHP Fatal error:  Uncaught UnderflowException: Frame must be coalesced before applying mask in D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\Frame.php:78
Stack trace:
#0 [internal function]: Ratchet\RFC6455\Messaging\Frame::Ratchet\RFC6455\Messaging\{closure}()
#1 D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\Frame.php(287): call_user_func()
#2 D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(216): Ratchet\RFC6455\Messaging\Frame->unMaskPayload()
#3 D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#4 D:\Install\discord-php-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123):
Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#5 D:\Install\discord-php-bot\vendor\react\stream\src\Util.php(71): Evenement\EventEmitter->emit()
#6 D:\Install\discord-php-bot\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123):
React\Stream\Util::React\Stre in D:\Install\discord-php-bot\vendor\ratchet\rfc6455\src\Messaging\Frame.php on line 78
```

Stable v6.0.3 is also affected.

Might be related to the ratchet library.

**Comment by key2peace** [comment]
**The Fix**

run `` composer require cweagans/composer-patches``
```
Using version ^1.7 for cweagans/composer-patches
./composer.json has been updated
Running composer update cweagans/composer-patches
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking cweagans/composer-patches (1.7.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.7.2): Extracting archive
cweagans/composer-patches contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "cweagans/composer-patches" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Generating autoload files
19 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
Add the following to your composer.json (before "config"):
```
    "extra": {
        "patches": {
            "ratchet/rfc6455": {
                "32bit support for 2Gb chunks" : "https://patch-diff.githubusercontent.com/raw/ratchetphp/RFC6455/pull/65.patch"
            }
        },
        "composer-exit-on-patch-failure": true
    },
```

run ``composer update``
```
Gathering patches for root package.
Removing package ratchet/rfc6455 so that it can be re-installed and re-patched.
  - Removing ratchet/rfc6455 (v0.3.1)
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing ratchet/rfc6455 (v0.3.1): Extracting archive
  - Applying patches for ratchet/rfc6455
    https://patch-diff.githubusercontent.com/raw/ratchetphp/RFC6455/pull/65.patch (32bit support for 2Gb chunks)

Generating autoload files
19 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
Enjoy!

**Comment by SQKo** [comment]
Since the PR is now merged (not released yet), you can temporarily apply the patch by:
`composer require ratchet/rfc6455:"dev-master#382a3ed as 0.3.1`

We'll add the patched version to requirements ASAP once it's released.

**Comment by valzargaming** [comment]
Closing this as stale, we now require `ratchet/rfc6455": "^0.3.1 || ^0.4.0"`
