### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by xWildFire** [discord-php/DiscordPHP#839]
**Environment**
- PHP Version:
    - 8.0/8.1
- DiscordPHP Version:
    - latest dev-master

**Describe the bug**
I don't know if that's a discord bug or discordphp bug, but i've on my server some buttons e.g. accept rules, give voucher etc. 
It's working fine, but after a certain time its throwing an error Unknown interaction on first click after specific unuse time and then is working fine like before. I need interactions to work everytime on first click without errors :/

```
[28.06.2022, 09:08:19] [WARNING] REQ POST interactions/991238583979618364/XXX/callback failed: Discord\Http\Exceptions\NotFoundException: Not Found - {
    "message": "Unknown interaction",
    "code": 10062
} in /home/wildcord2/web/wildcord/vendor/discord-php/http/src/Discord/Http.php:459
Stack trace:
#0 /home/wildcord2/web/wildcord/vendor/discord-php/http/src/Discord/Http.php(348): Discord\Http\Http->handleError()
#1 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(42): Discord\Http\Http->Discord\Http\{closure}()
#2 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done()
#3 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#4 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#5 /home/wildcord2/web/wildcord/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}()
#6 /home/wildcord2/web/wildcord/vendor/react/http/src/Io/Transaction.php(90): React\Promise\Deferred->resolve()
#7 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Io\Transaction->React\Http\Io\{closure}()
#8 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#9 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#10 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#11 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#12 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done()
#13 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#14 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#15 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#16 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done()
#17 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#18 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#19 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#20 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done()
#21 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#22 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#23 /home/wildcord2/web/wildcord/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#24 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done()
#25 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#26 /home/wildcord2/web/wildcord/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#27 /home/wildcord2/web/wildcord/vendor/react/promise-stream/src/functions.php(79): React\Promise\Promise::React\Promise\{closure}()
#28 /home/wildcord2/web/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}()
#29 /home/wildcord2/web/wildcord/vendor/react/http/src/Io/ReadableBodyStream.php(50): Evenement\EventEmitter->emit()
#30 /home/wildcord2/web/wildcord/vendor/react/http/src/Io/ReadableBodyStream.php(151): React\Http\Io\ReadableBodyStream->close()
#31 /home/wildcord2/web/wildcord/vendor/react/http/src/Io/ReadableBodyStream.php(33): React\Http\Io\ReadableBodyStream->handleEnd()
#32 /home/wildcord2/web/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\ReadableBodyStream->React\Http\Io\{closure}()
#33 /home/wildcord2/web/wildcord/vendor/react/http/src/Client/Request.php(163): Evenement\EventEmitter->emit()
#34 /home/wildcord2/web/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Client\Request->handleData()
#35 /home/wildcord2/web/wildcord/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#36 /home/wildcord2/web/wildcord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#37 /home/wildcord2/web/wildcord/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#38 /home/wildcord2/web/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData()
#39 /home/wildcord2/web/wildcord/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#40 /home/wildcord2/web/wildcord/src/WildCord/App.php(439): React\EventLoop\StreamSelectLoop->run()
#41 /home/wildcord2/web/wildcord/bot.php(10): WildCord\App->run()
#42 {main}
```

**Comment by SQKo** [comment]
Sounds like unstable response time. I can't really tell without the codes, but as you said sometimes it doesn't work and sometimes it works again, then it is most likely caused to the bot failed to respond in time. If you have code that possible takes long, you will have to defer it and follow up later. Library is not supposed to measure this for your code performance, you have to handle it by yourself by catching that exception and handle it like telling user to try again. It is impossible to achieve 100% button always work. Factors caused from API side might also be the reason.

**Comment by xWildFire** [comment]
Hmm i don't think its taking more than 3 seconds because the code just adds member to role and sends response.
I will check it one more time but a time tracker is a nice idea i think.

**Comment by SQKo** [comment]
Please go on use the `dev-interaction-time` e6c4c03 should theoritically help you determine which interaction is slow

I purposedly sleep for 2 seconds to simulate it:
```php
$discord->listenCommand('ping', function (Interaction $interaction) {
    sleep(2);
    $interaction->respondWithMessage(MessageBuilder::new()->setContent("OK"));
});
```


```
[2022-06-28T08:44:09.252558+00:00] DiscordPHP.DEBUG: Received Interaction#897 991262718004834314 in 0.25699996948242 s [] []
[2022-06-28T08:44:11.268447+00:00] DiscordPHP.DEBUG: Responding Interaction#897 991262718004834314 from 2.2569999694824 s ago [] []
[2022-06-28T08:44:11.269058+00:00] DiscordPHP.DEBUG: BUCKET postinteractions/:interaction_id/:interaction_token/callback queued REQ POST interactions/991262718004834314/xxx/callback [] []
[2022-06-28T08:44:11.677361+00:00] DiscordPHP.DEBUG: REQ POST interactions/991262718004834314/xxx/callback 
successful [] []
[2022-06-28T08:44:11.678324+00:00] DiscordPHP.DEBUG: http not checking {"waiting":0,"empty":true} []
[2022-06-28T08:44:11.678838+00:00] DiscordPHP.DEBUG: Responded Interaction#897 991262718004834314 within 2.2569999694824 s [] []
```
And the interaction responded with "OK" in 2.2569999694824 seconds as it's still below 3 seconds.

**Comment by SQKo** [comment]
While indeed it's true that you responded to the interaction immediately after it is created, the abnormal part here is you get the Interaction after 12 seconds since it was created
`[29.06.2022, 21:42:28] [DEBUG] Received Interaction#32925 991790727887605870 in 12.222471952438 s `

Something is slowing down your gateway connection, you need to calculate & benchmark the time on another events to confirm this

**Comment by xWildFire** [comment]
Ok i think we can close, after check "acknowledge" at the beginning helped with tapping buttons after long unuse time probably smth was slowing it down randomly. 
The only funny thing is this interaction which is received in 12s when im spamming button, but i need take some time and watch what delays that.
