### ISSUE TITLE
VoiceClient not working for me

### ISSUE THREAD

**Issue by Dark-night45** [discord-php/DiscordPHP#904]
**Environment**
- PHP Version:
    - 8.1.8
- DiscordPHP Version:
    - 7.3.0

**Description**
I have problem with play music from file in voice
when i run command, bot joined to voice but no sound.
in console i don't get any error. also i use debug code but no error.
i have all requirements too but file not played in voice.

**Code** : 
```php
    $voiceChannel = $message->guild->channels->get('id', '922503052420849684');
    $discord->joinVoiceChannel($voiceChannel, false, false)->then(function (VoiceClient $vc) {
      echo "Music Played";
      $vc->playFile('gg.mp3'); //the file is in code folder and i try __DIR__ too
    });
```

Edit : Update discordphp version

**Comment by key2peace** [comment]
which operating system are you using for your bot?

**Comment by Dark-night45** [comment]
Windows 10 Enterprise x64

**Comment by key2peace** [comment]
can you try again with current dev-master?

**Comment by Dark-night45** [comment]
I use normal master 
but now i updated it(v7.3.3) but my music file not played 
also i tested dev-master, but with dev-master i can't run the bot and this is the error message i got :
```
PHP Fatal error:  Uncaught Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "pmChannels" does not exist. Defined options are: "cacheInterface", "cacheSweep", "disabledEvents", "dnsConfig", "intents", "loadAllMembers", "logger", "loop", "retrieveBans", "shardCount", "shardId", "socket_options", "storeMessages", "token". in C:\xampp\htdocs\back now\bot\vendor\symfony\options-resolver\OptionsResolver.php:871
Stack trace:
#0 C:\xampp\htdocs\back now\bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(1422): Symfony\Component\OptionsResolver\OptionsResolver->resolve()
#1 C:\xampp\htdocs\back now\bot\vendor\team-reflex\discord-php\src\Discord\Discord.php(362): Discord\Discord->resolveOptions()
#2 C:\xampp\htdocs\back now\bot\index.php(44): Discord\Discord->__construct()
#3 {main}
  thrown in C:\xampp\htdocs\back now\bot\vendor\symfony\options-resolver\OptionsResolver.php on line 871
```

**Comment by SQKo** [comment]
> but with dev-master i can't run the bot and this is the error message i got :

Remove 'pmChannels' from your Discord options, it is no longer available in v10
```php
$discord = new Discord([
    'pmChannels' => ... // remove this
]);
```

**Comment by Dark-night45** [comment]
My bot run successfully
But no command worked and no error was displayed in the console

**Comment by key2peace** [comment]
is your bot verified? is the command a message one without mention or through slash? do you have message_content intent enabled?

**Comment by Dark-night45** [comment]
My bot not verified, i don't have any slash command and message_content is enabled

**Comment by key2peace** [comment]
is it also enabled in the intents defined in the options for $discord = new Discord()?

**Comment by Dark-night45** [comment]
i see the following issue, but if my bot return empty, then why functions like join voice not working

**Comment by key2peace** [comment]
I don't have any such issues as you described above, also, in regards to joining a voice channel, nothing really changed, so this should simply work, even on your 7.3.3, show me your discord construct (without the token)

**Comment by Dark-night45** [comment]
```php 
include __DIR__ . '/vendor/autoload.php';
require_once('secret.php');
$GLOBALS['prefix'] = '.';
$token = get_token();

$discord = new Discord([
  'token' => $token,
  'loadAllMembers' => false,
  'storeMessages' => false,
  // 'pmChannels' => false
  // 'dnsConfig' => '8.8.8.8'
]);

$discord->on('ready', function(Discord $discord){
  echo "Bot is online";
});
$discord->on('ready', function($discord) {
  $activity = $discord->factory(Activity::class, [
    'name' => 'KC',
    'type' => Activity::TYPE_COMPETING
  ]);
  $discord->updatePresence($activity, false, "idle", false);
});

$discord->on('error', function ($e) {
  echo emit('udp-error', [$e]);
});
$discord->run();
```

**Comment by bariscodefxy** [comment]
> My bot run successfully But no command worked and no error was displayed in the console

@Dark-night45  Hello, I know it's late but I updated my [Hiro-Bot](https://github.com/bariscodefxy/Hiro-Discord-Bot) and commands were not worked for me too. I fixed with adding intent, 'Intents::MESSAGE_CONTENT'.

Example from my bot:
```php
$bot = new Hiro([
    'token' => $_ENV['TOKEN'],
    'prefix' => $_ENV['PREFIX'],
    'shardId' => $shard_id,
    'shardCount' => $shard_count,
    'caseInsensitiveCommands' => true,
    'loadAllMembers' => true,
    'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS | Intents::MESSAGE_CONTENT
]);
``` 

I'm seeing you're not using intents so you can fix that with adding this to array:
```php
    'intents' => Intents::getDefaultIntents() | Intents::GUILD_MEMBERS | Intents::MESSAGE_CONTENT
```

If you don't wanna to use GUILD_MEMBERS intent,
```php
    'intents' => Intents::getDefaultIntents() | Intents::MESSAGE_CONTENT
```
this is works too.

**Comment by Steveb-p** [comment]
Had the same issue. Promise seemed stuck in an unresolved state after UDP connection was established (event listeners for the voice status change never fired). Updating the library to current dev-master resolved the issue.

Seems like those events are no longer emitted on version pre 10.0-RC.

**Comment by valzargaming** [comment]
Closing as resolved for now as we've been unable to replicate this on the latest dev-master. #1300 is also under review and using the newer latest (v8) gateway, which may resolve some of the issues we were seeing.
